server:
  port: 8086
spring:
    application:
        name: flightmgmt-ws
    datasource:
        url: jdbc:mysql://localhost:3306/flightmgmt
        username: root
        password: pass@word1
        #driver-class-name: com.mysql.jdbc.Driver
    h2:
        console:
            enabled: true
            settings:
                web-allow-others: true
            path: /h2
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        defer-datasource-initialization: true
        generate-ddl: true
    security:
        user:
            name: nilay
            password: pass@1234
management:
    endpoints:
        web:
            exposure:
                include: '*'
logging:
    file:
        name: flightuser-ws.log
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost