server:
  port: 9191
spring:
  cloud:
    gateway:
      routes:
      - id: flightuser-ws
        uri: lb://flightuser-ws
        predicates:
        - Path=/api/v1.0/user/flight/**
      - id: flightadmin-ws
        uri: lb://flightadmin-ws
        predicates:
        - Path=/api/v1.0/admin/flight/**
      - id: flightmgmt-ws
        uri: lb://flightmgmt-ws
        predicates:
        - Path=/api/v1.0/flightmgmt/**     # default-filters:     # - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin     # globalcors:      #  cors-configurations:      #    '[/**]':
       #       allowedOrigins:"*"
        #      allowedMethods:"*"
         #     allowedHeaders:"*"      discovery:        locator:          enabled: true          lower-case-service-id: true      globalcors:        add-to-simple-url-handler-mapping: true

  application:
    name: api-gateway
             h2:    console:      enabled: true  main:    web-application-type: reactive    allow-bean-definition-overriding: true  #security:   # user:     # name: abc     # password: password    allow-circular-references: true  
          

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
jwt:
  secret:
   javainuse
